name       : gst-plugins-base
version    : 0.10.36
release    : 1
source     :
    - http://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-0.10.36.tar.xz : 1fe45c3894903001d4d008b0713dab089f53726dcb5842d5b40c2595a984e64a
license    :
    - GPL-2.0
    - LGPL-2.0
summary    : Streaming media framework
description: |
    GStreamer is a streaming media framework that enables applications to share a common set of plugins for things like video encoding and decoding, audio encoding and decoding, audio and video filters, audio visualisation, web streaming and anything else that streams in real-time or otherwise. This package only provides base functionality and libraries.
builddeps  :
    - pkgconfig(gstreamer-0.10)
    - pkgconfig(x11)
    - pkgconfig(alsa)
    - pkgconfig(vorbis)
    - pkgconfig(ogg)
    - pkgconfig(theora)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
